### PR TITLE
Update appdata

### LINKED ISSUE #3: Metadata is missing
This points to the upstream metainfo file https://github.com/flathub/io.github.Hexchat.Plugin.Perl/blob/8fb2aeec9e11bdc57584b4dd81e1e33fb9da209e/io.github.Hexchat.Plugin.Perl.json#L63 but neither the 2.14.3 archive nor git has that file https://github.com/hexchat/hexchat/tree/master/data/misc.

I guess as a result this doesn't show up in GNOME Software as an addon/separate app.

### PR DESCRIPTION
**Pull request by bbhtt**
Hopefully fixes https://github.com/flathub/io.github.Hexchat.Plugin.Perl/issues/3

Edit. Seems to work:

image

### CODE REVIEW

**Comment by bbhtt** [comment]
bot build https://github.com/flathub/io.github.Hexchat.Plugin.Perl

**Comment by bbhtt** [comment]
bot, build io.github.Hexchat.Plugin.Perl

**Comment by hfiguiere** [comment]
I'm actualy surprised the plugin works given that it is build against a different runtime than the app.

**Comment by bbhtt** [comment]
> I'm actualy surprised the plugin works given that it is build against a different runtime than the app.

I can address that in a separate PR once this is done and I come back from work. 40 is EOL anyways and the sources are outdated as well. The OTR plugin also needs a runtime bump.

**Pull request merged**
